/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
 
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export { Activity } from './models/Activity';
export type { ActivityCharts } from './models/ActivityCharts';
export { ActivityFilter } from './models/ActivityFilter';
export type { ActivityHRCurve } from './models/ActivityHRCurve';
export type { ActivityHRCurvePayload } from './models/ActivityHRCurvePayload';
export type { ActivityId } from './models/ActivityId';
export type { ActivityMini } from './models/ActivityMini';
export type { ActivityPowerCurve } from './models/ActivityPowerCurve';
export type { ActivityPowerCurvePayload } from './models/ActivityPowerCurvePayload';
export type { ActivitySearchResult } from './models/ActivitySearchResult';
export type { ActivityStream } from './models/ActivityStream';
export type { ActivityWeather } from './models/ActivityWeather';
export type { ActivityWeatherSummary } from './models/ActivityWeatherSummary';
export { ActivityWithIntervals } from './models/ActivityWithIntervals';
export type { Anomaly } from './models/Anomaly';
export type { ApplyPlanDTO } from './models/ApplyPlanDTO';
export { Athlete } from './models/Athlete';
export type { AthleteForProfile } from './models/AthleteForProfile';
export type { AthleteProfile } from './models/AthleteProfile';
export type { AthleteRoute } from './models/AthleteRoute';
export type { AthleteSearchResult } from './models/AthleteSearchResult';
export { AthleteTrainingAvailability } from './models/AthleteTrainingAvailability';
export type { AthleteTrainingPlan } from './models/AthleteTrainingPlan';
export type { AthleteTrainingPlanUpdate } from './models/AthleteTrainingPlanUpdate';
export { AthleteUpdateDTO } from './models/AthleteUpdateDTO';
export type { Attachment } from './models/Attachment';
export type { BestEfforts } from './models/BestEfforts';
export type { Bucket } from './models/Bucket';
export { CategorySummary } from './models/CategorySummary';
export { Chat } from './models/Chat';
export { ChatMember } from './models/ChatMember';
export type { Closest } from './models/Closest';
export type { CoachTick } from './models/CoachTick';
export type { Course } from './models/Course';
export { CreateFolderDTO } from './models/CreateFolderDTO';
export type { Curve } from './models/Curve';
export { CustomItem } from './models/CustomItem';
export type { DataCurve } from './models/DataCurve';
export type { DataCurvePt } from './models/DataCurvePt';
export type { DataCurveSetHRCurve } from './models/DataCurveSetHRCurve';
export type { DataCurveSetPaceCurve } from './models/DataCurveSetPaceCurve';
export type { DataCurveSetPowerCurve } from './models/DataCurveSetPowerCurve';
export type { DeleteEventsResponse } from './models/DeleteEventsResponse';
export type { Display } from './models/Display';
export type { DoomedEvent } from './models/DoomedEvent';
export type { DuplicateEventsDTO } from './models/DuplicateEventsDTO';
export type { DuplicateWorkoutsDTO } from './models/DuplicateWorkoutsDTO';
export type { Effort } from './models/Effort';
export { Event } from './models/Event';
export { EventEx } from './models/EventEx';
export { Folder } from './models/Folder';
export { Forecast } from './models/Forecast';
export { Gear } from './models/Gear';
export type { GearReminder } from './models/GearReminder';
export type { GearStats } from './models/GearStats';
export { Hidden } from './models/Hidden';
export type { HRCurve } from './models/HRCurve';
export { HRLoadModel } from './models/HRLoadModel';
export type { HRRecovery } from './models/HRRecovery';
export { IcuAchievement } from './models/IcuAchievement';
export type { IcuSegment } from './models/IcuSegment';
export type { Ignore } from './models/Ignore';
export { Interval } from './models/Interval';
export type { IntervalGroup } from './models/IntervalGroup';
export type { IntervalsDTO } from './models/IntervalsDTO';
export type { MapData } from './models/MapData';
export type { Marker } from './models/Marker';
export { Message } from './models/Message';
export type { NewActivityMsg } from './models/NewActivityMsg';
export { NewCustomItem } from './models/NewCustomItem';
export { NewMessage } from './models/NewMessage';
export type { NewMsg } from './models/NewMsg';
export { PaceCurve } from './models/PaceCurve';
export type { PaceDistancesDTO } from './models/PaceDistancesDTO';
export { PaceModel } from './models/PaceModel';
export type { Plot } from './models/Plot';
export type { Pos } from './models/Pos';
export type { PowerCurve } from './models/PowerCurve';
export type { PowerHRCurve } from './models/PowerHRCurve';
export { PowerModel } from './models/PowerModel';
export type { PowerVsHRPlot } from './models/PowerVsHRPlot';
export type { PushError } from './models/PushError';
export type { Rank } from './models/Rank';
export type { RouteSimilarity } from './models/RouteSimilarity';
export type { SendResponse } from './models/SendResponse';
export { Settings } from './models/Settings';
export type { SharedWith } from './models/SharedWith';
export { SportInfo } from './models/SportInfo';
export { SportSettings } from './models/SportSettings';
export type { StravaGear } from './models/StravaGear';
export type { SummaryWithCats } from './models/SummaryWithCats';
export type { Time } from './models/Time';
export type { UpdateStreamsResult } from './models/UpdateStreamsResult';
export type { UploadResponse } from './models/UploadResponse';
export type { WeatherConfig } from './models/WeatherConfig';
export type { WeatherDTO } from './models/WeatherDTO';
export type { WeatherPoint } from './models/WeatherPoint';
export { Wellness } from './models/Wellness';
export type { WindRose } from './models/WindRose';
export type { WithCount } from './models/WithCount';
export { WithCourses } from './models/WithCourses';
export { WithSportSettings } from './models/WithSportSettings';
export { Workout } from './models/Workout';
export { WorkoutEx } from './models/WorkoutEx';
export type { ZoneInfo } from './models/ZoneInfo';
export type { ZoneSet } from './models/ZoneSet';
export type { ZoneTime } from './models/ZoneTime';

export { AktivitTenService } from './services/AktivitTenService';
export { AthletenService } from './services/AthletenService';
export { AusrStungService } from './services/AusrStungService';
export { BibliothekService } from './services/BibliothekService';
export { ChatsService } from './services/ChatsService';
export { CustomItemsService } from './services/CustomItemsService';
export { OAuthServerControllerService } from './services/OAuthServerControllerService';
export { RoutenService } from './services/RoutenService';
export { SharedEventsService } from './services/SharedEventsService';
export { SportService } from './services/SportService';
export { VeranstaltungenService } from './services/VeranstaltungenService';
export { WellnessService } from './services/WellnessService';
export { WetterService } from './services/WetterService';
